// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	provider "github.com/odpf/entropy/provider"
	mock "github.com/stretchr/testify/mock"
)

// ProviderRepository is an autogenerated mock type for the Repository type
type ProviderRepository struct {
	mock.Mock
}

type ProviderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProviderRepository) EXPECT() *ProviderRepository_Expecter {
	return &ProviderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: r
func (_m *ProviderRepository) Create(r *provider.Provider) error {
	ret := _m.Called(r)

	var r0 error
	if rf, ok := ret.Get(0).(func(*provider.Provider) error); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProviderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProviderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//  - r *provider.Provider
func (_e *ProviderRepository_Expecter) Create(r interface{}) *ProviderRepository_Create_Call {
	return &ProviderRepository_Create_Call{Call: _e.mock.On("Create", r)}
}

func (_c *ProviderRepository_Create_Call) Run(run func(r *provider.Provider)) *ProviderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*provider.Provider))
	})
	return _c
}

func (_c *ProviderRepository_Create_Call) Return(_a0 error) *ProviderRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetByURN provides a mock function with given fields: urn
func (_m *ProviderRepository) GetByURN(urn string) (*provider.Provider, error) {
	ret := _m.Called(urn)

	var r0 *provider.Provider
	if rf, ok := ret.Get(0).(func(string) *provider.Provider); ok {
		r0 = rf(urn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provider.Provider)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(urn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProviderRepository_GetByURN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByURN'
type ProviderRepository_GetByURN_Call struct {
	*mock.Call
}

// GetByURN is a helper method to define mock.On call
//  - urn string
func (_e *ProviderRepository_Expecter) GetByURN(urn interface{}) *ProviderRepository_GetByURN_Call {
	return &ProviderRepository_GetByURN_Call{Call: _e.mock.On("GetByURN", urn)}
}

func (_c *ProviderRepository_GetByURN_Call) Run(run func(urn string)) *ProviderRepository_GetByURN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ProviderRepository_GetByURN_Call) Return(_a0 *provider.Provider, _a1 error) *ProviderRepository_GetByURN_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// List provides a mock function with given fields: filter
func (_m *ProviderRepository) List(filter map[string]string) ([]*provider.Provider, error) {
	ret := _m.Called(filter)

	var r0 []*provider.Provider
	if rf, ok := ret.Get(0).(func(map[string]string) []*provider.Provider); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*provider.Provider)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProviderRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ProviderRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//  - filter map[string]string
func (_e *ProviderRepository_Expecter) List(filter interface{}) *ProviderRepository_List_Call {
	return &ProviderRepository_List_Call{Call: _e.mock.On("List", filter)}
}

func (_c *ProviderRepository_List_Call) Run(run func(filter map[string]string)) *ProviderRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]string))
	})
	return _c
}

func (_c *ProviderRepository_List_Call) Return(_a0 []*provider.Provider, _a1 error) *ProviderRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Migrate provides a mock function with given fields:
func (_m *ProviderRepository) Migrate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProviderRepository_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type ProviderRepository_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
func (_e *ProviderRepository_Expecter) Migrate() *ProviderRepository_Migrate_Call {
	return &ProviderRepository_Migrate_Call{Call: _e.mock.On("Migrate")}
}

func (_c *ProviderRepository_Migrate_Call) Run(run func()) *ProviderRepository_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProviderRepository_Migrate_Call) Return(_a0 error) *ProviderRepository_Migrate_Call {
	_c.Call.Return(_a0)
	return _c
}
