project_name: entropy

release:
  prerelease: auto
  draft: true

builds:
  - main: ./main.go
    id: "entropy"
    binary: entropy
    flags: [-a]
    ldflags:
      - -X github.com/goto/entropy/pkg/version.Version={{.Tag}}
      - -X github.com/goto/entropy/pkg/version.Commit={{.FullCommit}}
      - -X github.com/goto/entropy/pkg/version.BuildTime={{.Date}}
    goos: 
      - darwin
      - linux
      - windows
    goarch: 
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - replacements:
      darwin: macos
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^build'
      - '^ci'
      - '^chore'
      - '^refactor'

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - entropy
    dockerfile: Dockerfile
    image_templates:
      - 'docker.io/gotocompany/{{.ProjectName}}:latest'
      - 'docker.io/gotocompany/{{.ProjectName}}:{{ .Version }}'
      - 'docker.io/gotocompany/{{.ProjectName}}:{{ .Version }}-amd64'

brews:
  - name: entropy
    homepage: "https://github.com/goto/entropy"
    description: "Infrastructure orchestration tool."
    tap:
      owner: odpf
      name: homebrew-tap
    license: "Apache 2.0"
    folder: Formula
    dependencies:
      - name: git
    install: |-
      bin.install "entropy"
    commit_author:
      name: Rohil Surana
      email: rohilsurana96@gmail.com
