CREATE TABLE IF NOT EXISTS __queueTable__
(
    -- Job specification.
    id              TEXT      NOT NULL PRIMARY KEY,
    kind            TEXT      NOT NULL,
    status          TEXT      NOT NULL,
    run_at          TIMESTAMP NOT NULL,
    payload         bytea     NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT current_timestamp,
    updated_at      TIMESTAMP NOT NULL DEFAULT current_timestamp,

    -- Result generated by execution.
    result          bytea,
    attempts_done   INTEGER   NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMP,
    last_error      TEXT
);

CREATE INDEX IF NOT EXISTS idx___queueTable___kind ON __queueTable__ (kind);
CREATE INDEX IF NOT EXISTS idx___queueTable___status ON __queueTable__ (status);
CREATE INDEX IF NOT EXISTS idx___queueTable___run_at ON __queueTable__ (run_at);