// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	resource "github.com/odpf/entropy/core/resource"
	mock "github.com/stretchr/testify/mock"
)

// LoggableModule is an autogenerated mock type for the LoggableModule type
type LoggableModule struct {
	mock.Mock
}

type LoggableModule_Expecter struct {
	mock *mock.Mock
}

func (_m *LoggableModule) EXPECT() *LoggableModule_Expecter {
	return &LoggableModule_Expecter{mock: &_m.Mock}
}

// Act provides a mock function with given fields: r, action, params
func (_m *LoggableModule) Act(r resource.Resource, action string, params map[string]interface{}) (map[string]interface{}, error) {
	ret := _m.Called(r, action, params)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(resource.Resource, string, map[string]interface{}) map[string]interface{}); ok {
		r0 = rf(r, action, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(resource.Resource, string, map[string]interface{}) error); ok {
		r1 = rf(r, action, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoggableModule_Act_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Act'
type LoggableModule_Act_Call struct {
	*mock.Call
}

// Act is a helper method to define mock.On call
//  - r resource.Resource
//  - action string
//  - params map[string]interface{}
func (_e *LoggableModule_Expecter) Act(r interface{}, action interface{}, params interface{}) *LoggableModule_Act_Call {
	return &LoggableModule_Act_Call{Call: _e.mock.On("Act", r, action, params)}
}

func (_c *LoggableModule_Act_Call) Run(run func(r resource.Resource, action string, params map[string]interface{})) *LoggableModule_Act_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(resource.Resource), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *LoggableModule_Act_Call) Return(_a0 map[string]interface{}, _a1 error) *LoggableModule_Act_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Apply provides a mock function with given fields: r
func (_m *LoggableModule) Apply(r resource.Resource) (resource.Status, error) {
	ret := _m.Called(r)

	var r0 resource.Status
	if rf, ok := ret.Get(0).(func(resource.Resource) resource.Status); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Get(0).(resource.Status)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(resource.Resource) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoggableModule_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type LoggableModule_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//  - r resource.Resource
func (_e *LoggableModule_Expecter) Apply(r interface{}) *LoggableModule_Apply_Call {
	return &LoggableModule_Apply_Call{Call: _e.mock.On("Apply", r)}
}

func (_c *LoggableModule_Apply_Call) Run(run func(r resource.Resource)) *LoggableModule_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(resource.Resource))
	})
	return _c
}

func (_c *LoggableModule_Apply_Call) Return(_a0 resource.Status, _a1 error) *LoggableModule_Apply_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ID provides a mock function with given fields:
func (_m *LoggableModule) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// LoggableModule_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type LoggableModule_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *LoggableModule_Expecter) ID() *LoggableModule_ID_Call {
	return &LoggableModule_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *LoggableModule_ID_Call) Run(run func()) *LoggableModule_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LoggableModule_ID_Call) Return(_a0 string) *LoggableModule_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

// Log provides a mock function with given fields: ctx, r, filter
func (_m *LoggableModule) Log(ctx context.Context, r resource.Resource, filter map[string]string) (<-chan resource.LogChunk, error) {
	ret := _m.Called(ctx, r, filter)

	var r0 <-chan resource.LogChunk
	if rf, ok := ret.Get(0).(func(context.Context, resource.Resource, map[string]string) <-chan resource.LogChunk); ok {
		r0 = rf(ctx, r, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan resource.LogChunk)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, resource.Resource, map[string]string) error); ok {
		r1 = rf(ctx, r, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoggableModule_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type LoggableModule_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//  - ctx context.Context
//  - r resource.Resource
//  - filter map[string]string
func (_e *LoggableModule_Expecter) Log(ctx interface{}, r interface{}, filter interface{}) *LoggableModule_Log_Call {
	return &LoggableModule_Log_Call{Call: _e.mock.On("Log", ctx, r, filter)}
}

func (_c *LoggableModule_Log_Call) Run(run func(ctx context.Context, r resource.Resource, filter map[string]string)) *LoggableModule_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(resource.Resource), args[2].(map[string]string))
	})
	return _c
}

func (_c *LoggableModule_Log_Call) Return(_a0 <-chan resource.LogChunk, _a1 error) *LoggableModule_Log_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Validate provides a mock function with given fields: r
func (_m *LoggableModule) Validate(r resource.Resource) error {
	ret := _m.Called(r)

	var r0 error
	if rf, ok := ret.Get(0).(func(resource.Resource) error); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoggableModule_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type LoggableModule_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//  - r resource.Resource
func (_e *LoggableModule_Expecter) Validate(r interface{}) *LoggableModule_Validate_Call {
	return &LoggableModule_Validate_Call{Call: _e.mock.On("Validate", r)}
}

func (_c *LoggableModule_Validate_Call) Run(run func(r resource.Resource)) *LoggableModule_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(resource.Resource))
	})
	return _c
}

func (_c *LoggableModule_Validate_Call) Return(_a0 error) *LoggableModule_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}
