// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	resource "github.com/odpf/entropy/core/resource"
	mock "github.com/stretchr/testify/mock"
)

// LoggableModule is an autogenerated mock type for the LoggableModule type
type LoggableModule struct {
	mock.Mock
}

type LoggableModule_Expecter struct {
	mock *mock.Mock
}

func (_m *LoggableModule) EXPECT() *LoggableModule_Expecter {
	return &LoggableModule_Expecter{mock: &_m.Mock}
}

// ID provides a mock function with given fields:
func (_m *LoggableModule) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// LoggableModule_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type LoggableModule_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *LoggableModule_Expecter) ID() *LoggableModule_ID_Call {
	return &LoggableModule_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *LoggableModule_ID_Call) Run(run func()) *LoggableModule_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LoggableModule_ID_Call) Return(_a0 string) *LoggableModule_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

// Log provides a mock function with given fields: ctx, r, filter
func (_m *LoggableModule) Log(ctx context.Context, r resource.Resource, filter map[string]string) (<-chan resource.LogChunk, error) {
	ret := _m.Called(ctx, r, filter)

	var r0 <-chan resource.LogChunk
	if rf, ok := ret.Get(0).(func(context.Context, resource.Resource, map[string]string) <-chan resource.LogChunk); ok {
		r0 = rf(ctx, r, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan resource.LogChunk)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, resource.Resource, map[string]string) error); ok {
		r1 = rf(ctx, r, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoggableModule_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type LoggableModule_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//  - ctx context.Context
//  - r resource.Resource
//  - filter map[string]string
func (_e *LoggableModule_Expecter) Log(ctx interface{}, r interface{}, filter interface{}) *LoggableModule_Log_Call {
	return &LoggableModule_Log_Call{Call: _e.mock.On("Log", ctx, r, filter)}
}

func (_c *LoggableModule_Log_Call) Run(run func(ctx context.Context, r resource.Resource, filter map[string]string)) *LoggableModule_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(resource.Resource), args[2].(map[string]string))
	})
	return _c
}

func (_c *LoggableModule_Log_Call) Return(_a0 <-chan resource.LogChunk, _a1 error) *LoggableModule_Log_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Plan provides a mock function with given fields: ctx, spec, act
func (_m *LoggableModule) Plan(ctx context.Context, spec resource.ModuleSpec, act resource.Action) (*resource.Resource, error) {
	ret := _m.Called(ctx, spec, act)

	var r0 *resource.Resource
	if rf, ok := ret.Get(0).(func(context.Context, resource.ModuleSpec, resource.Action) *resource.Resource); ok {
		r0 = rf(ctx, spec, act)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resource.Resource)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, resource.ModuleSpec, resource.Action) error); ok {
		r1 = rf(ctx, spec, act)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoggableModule_Plan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Plan'
type LoggableModule_Plan_Call struct {
	*mock.Call
}

// Plan is a helper method to define mock.On call
//  - ctx context.Context
//  - spec resource.ModuleSpec
//  - act resource.Action
func (_e *LoggableModule_Expecter) Plan(ctx interface{}, spec interface{}, act interface{}) *LoggableModule_Plan_Call {
	return &LoggableModule_Plan_Call{Call: _e.mock.On("Plan", ctx, spec, act)}
}

func (_c *LoggableModule_Plan_Call) Run(run func(ctx context.Context, spec resource.ModuleSpec, act resource.Action)) *LoggableModule_Plan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(resource.ModuleSpec), args[2].(resource.Action))
	})
	return _c
}

func (_c *LoggableModule_Plan_Call) Return(_a0 *resource.Resource, _a1 error) *LoggableModule_Plan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Sync provides a mock function with given fields: ctx, spec
func (_m *LoggableModule) Sync(ctx context.Context, spec resource.ModuleSpec) (*resource.State, error) {
	ret := _m.Called(ctx, spec)

	var r0 *resource.State
	if rf, ok := ret.Get(0).(func(context.Context, resource.ModuleSpec) *resource.State); ok {
		r0 = rf(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resource.State)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, resource.ModuleSpec) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoggableModule_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type LoggableModule_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//  - ctx context.Context
//  - spec resource.ModuleSpec
func (_e *LoggableModule_Expecter) Sync(ctx interface{}, spec interface{}) *LoggableModule_Sync_Call {
	return &LoggableModule_Sync_Call{Call: _e.mock.On("Sync", ctx, spec)}
}

func (_c *LoggableModule_Sync_Call) Run(run func(ctx context.Context, spec resource.ModuleSpec)) *LoggableModule_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(resource.ModuleSpec))
	})
	return _c
}

func (_c *LoggableModule_Sync_Call) Return(_a0 *resource.State, _a1 error) *LoggableModule_Sync_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
