// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	resource "github.com/odpf/entropy/core/resource"
	mock "github.com/stretchr/testify/mock"
)

// ModuleRegistry is an autogenerated mock type for the ModuleRegistry type
type ModuleRegistry struct {
	mock.Mock
}

type ModuleRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *ModuleRegistry) EXPECT() *ModuleRegistry_Expecter {
	return &ModuleRegistry_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: id
func (_m *ModuleRegistry) Get(id string) (resource.Module, error) {
	ret := _m.Called(id)

	var r0 resource.Module
	if rf, ok := ret.Get(0).(func(string) resource.Module); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.Module)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ModuleRegistry_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ModuleRegistry_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//  - id string
func (_e *ModuleRegistry_Expecter) Get(id interface{}) *ModuleRegistry_Get_Call {
	return &ModuleRegistry_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *ModuleRegistry_Get_Call) Run(run func(id string)) *ModuleRegistry_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ModuleRegistry_Get_Call) Return(_a0 resource.Module, _a1 error) *ModuleRegistry_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Register provides a mock function with given fields: m
func (_m *ModuleRegistry) Register(m resource.Module) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(resource.Module) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ModuleRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type ModuleRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//  - m resource.Module
func (_e *ModuleRegistry_Expecter) Register(m interface{}) *ModuleRegistry_Register_Call {
	return &ModuleRegistry_Register_Call{Call: _e.mock.On("Register", m)}
}

func (_c *ModuleRegistry_Register_Call) Run(run func(m resource.Module)) *ModuleRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(resource.Module))
	})
	return _c
}

func (_c *ModuleRegistry_Register_Call) Return(_a0 error) *ModuleRegistry_Register_Call {
	_c.Call.Return(_a0)
	return _c
}
