// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	worker "github.com/goto/entropy/pkg/worker"
)

// AsyncWorker is an autogenerated mock type for the AsyncWorker type
type AsyncWorker struct {
	mock.Mock
}

type AsyncWorker_Expecter struct {
	mock *mock.Mock
}

func (_m *AsyncWorker) EXPECT() *AsyncWorker_Expecter {
	return &AsyncWorker_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function with given fields: ctx, jobs
func (_m *AsyncWorker) Enqueue(ctx context.Context, jobs ...worker.Job) error {
	_va := make([]interface{}, len(jobs))
	for _i := range jobs {
		_va[_i] = jobs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...worker.Job) error); ok {
		r0 = rf(ctx, jobs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AsyncWorker_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type AsyncWorker_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - jobs ...worker.Job
func (_e *AsyncWorker_Expecter) Enqueue(ctx interface{}, jobs ...interface{}) *AsyncWorker_Enqueue_Call {
	return &AsyncWorker_Enqueue_Call{Call: _e.mock.On("Enqueue",
		append([]interface{}{ctx}, jobs...)...)}
}

func (_c *AsyncWorker_Enqueue_Call) Run(run func(ctx context.Context, jobs ...worker.Job)) *AsyncWorker_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]worker.Job, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(worker.Job)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *AsyncWorker_Enqueue_Call) Return(_a0 error) *AsyncWorker_Enqueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AsyncWorker_Enqueue_Call) RunAndReturn(run func(context.Context, ...worker.Job) error) *AsyncWorker_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewAsyncWorker interface {
	mock.TestingT
	Cleanup(func())
}

// NewAsyncWorker creates a new instance of AsyncWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAsyncWorker(t mockConstructorTestingTNewAsyncWorker) *AsyncWorker {
	mock := &AsyncWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
